language: python
python: "3.4"

# command to install dependencies
install: "make install"

# command to run tests
script: "make test"

# setting the notification level to none
notifications:
  email: false
